### ISSUE TITLE
Highest bits in Sv39

### ISSUE THREAD

**Issue by janhoogerbrugge** [pulp-platform/ariane#136]
The spec says:

  Load and store effective addresses, which are 64 bits, must have bits 63–39 
  all equal to bit 38, or else a page-fault exception will occur.

The code says:
```
  // check that all bits in the address >= 39 are equal
  if (!((&lsu_ctrl.vaddr[63:39]) == 1'b1 || (|lsu_ctrl.vaddr[63:39]) == 1'b0)) ...
```
So then the 39 in the code should be 38?

Jan

**Comment by zarubaf** [comment]
Yes you are absolutely right. Unfortunately there is some other issue with this code: Actually we should not test this in machine mode. @msfschaffner has a patch for this and will also include the issue you address. Thanks for bringing this up.

**Comment by msfschaffner** [comment]
Thanks for reporting this. I'll include it in the patch that fixes the page-fault checks.
