### ISSUE TITLE
fpga Makefile target not robust

### ISSUE THREAD

**Issue by jrrk** [pulp-platform/ariane#146]
Top-level Ariane Makefile has a target called fpga. Top-level Ariane also has a subdirectory called fpga. Therefore, if the directory is newer than any of the dependencies, fpga target will not be built even if it needs to be.

Solution: rename fpga target or perhaps making it .PHONY might solve the problem
Workaround: make fpga -B

**Comment by zarubaf** [comment]
Thanks. Fixed in the latest `ariane_next`.
