### ISSUE TITLE
Data cache on FPGA design not working? 

### ISSUE THREAD

**Issue by janhoogerbrugge** [pulp-platform/ariane#168]
Hi,

When I run the following code on Ariane on Verilator I get a CPI of 1.5:

    for(int i = 0; i < 10000; i++)
      asm volatile ("ld %0, 0(%1)" : "=r"(dummy2) : "r"(&dummy));

I would expect that with a branch that is predictable and a load that always hits the dcache, the 
CPI would be closer to one but it is a lot better than when I run the same code (compiled
with -O) on the Genesys 2 board. Then I get a CPI of 11.2! It seems that the data cache
is not used. Any idea what is wrong? The bitfile on https://github.com/pulp-platform/ariane/releases
gives the same result.

This loop (without dcache accesses) gives a CPI of 1.3 on Verilator and a CPI of 2.4 on the FPGA:

    for(int i = 0; i < 10000; i++)
      asm volatile("");

Regards,
Jan

**Comment by zarubaf** [comment]
Hi Jan, 

sorry for the long radio silence. On the FPGA you have to face the much larger re-fill path which goes through the DRAM controller. I don't have any exact numbers but I would expect this to be in the orders of 50 - 100 cycles. My suggestion would be to warm up the caches e.g.: by doing the above twice and only measuring CPI on the second run. 

Furthermore,  make sure that the amount of memory you are loading actually fits into the (small) data cache. As we do not have an L2 cache every miss is quite costly. The access latency should actually be the only difference between simulation and FPGA. If your memory address (physical) is above `0x8000_0000` all the accesses should be cached. 

Can you elaborate a bit on how you are running the programs, e.g.: Linux, bare-metal, `pk` with `fesvr`?

Best,
Florian

P.S.: Also make sure that you are not using the debugger, it will invalidate all the cache-lines on each access.

**Comment by janhoogerbrugge** [comment]
Hi Florian,

Attached is a small program test increases the working set of a program by increasing the stride
by which it steps through a buffer in memory. On the Verilator simulator you can see that
around 16 to 32KB things do not fit in the dcache anymore and the CPI starts to increase.
(I expect that the effect would have been more clear with LRU replacement instead
of the used random replacement).

working_set =  0KB, 101396 instructions, 133335 cycles, CPI = 1.314993
working_set =  4KB, 101396 instructions, 133610 cycles, CPI = 1.317705
working_set =  8KB, 101396 instructions, 146653 cycles, CPI = 1.446339
working_set = 16KB, 101396 instructions, 179670 cycles, CPI = 1.771963
working_set = 32KB, 101396 instructions, 294517 cycles, CPI = 2.904622
working_set = 64KB, 101396 instructions, 449212 cycles, CPI = 4.430274

This is what happens on the FPGA:

working_set =  0KB, 107977 instructions, 1124905 cycles, CPI = 10.418006
working_set =  4KB, 107956 instructions, 1124738 cycles, CPI = 10.418486
working_set =  8KB, 111236 instructions, 1189904 cycles, CPI = 10.697112
working_set = 16KB, 113172 instructions, 1236584 cycles, CPI = 10.926590
working_set = 32KB, 107958 instructions, 1124950 cycles, CPI = 10.420256
working_set = 64KB, 107954 instructions, 1139729 cycles, CPI = 10.557543

As you can see the CPI is high and independent of the working set.

The cycle count of 64KB working set is 1139729. If we do 10 * 4096 iterations
then that means 27 cycles per iteration. If we subtract a few cycles for the
loop overhead then the latency of the DRAM will be something like 20 or 25
cycles. I expect that a GHz core where L1 misses go to a L2 cache will
experience latencies that are in the same range, especially when the L2 is
shared my multiple cores and instruction caches.

[cachetest.c.gz](https://github.com/pulp-platform/ariane/files/2832100/cachetest.c.gz)
[cachetest.elf.gz](https://github.com/pulp-platform/ariane/files/2832101/cachetest.elf.gz)

**Comment by zarubaf** [comment]
Hi Jan,

thanks for the effort you put into this. Just to be sure: How do you run the program on FPGA/Verilator? `pk` uses the debugger and clears the cache on every access (but it doesn't seem to be a big problem as the CPI in the verilator case seems to be reasonable).

There should be performance counters for the cache misses: https://github.com/pulp-platform/ariane/wiki/Performance-Counters
You might want to consider reading them as well and comparing. If that turns out to be different between the FPGA and the simulation we need to dig a bit deeper. To be honest I've never profiled Linux applications.  

Best,
Florian

**Comment by janhoogerbrugge** [comment]
Hi Florian,

On Verilator the code runs with pk and on the FPGA it runs as user code on Linux.

When I use the performance counters from the webpage with indices 0xBxx then I get an illegal instruction (both on FPGA/Linux and Verilator/pk) as these are for machine level. If I replace them by 0xCxx like this:

```
  for(int i = 0; i < 10; i++)
  {
    if(i == 1)
    {
      instret_start = read_csr(instret);
      cycle_start = read_csr(cycle);
      miss_start = read_csr(0xC04);
      load_start = read_csr(0xC07);
      store_start = read_csr(0xC08);
    }

    for(int j = 0; j < max_j; j += 4)
    {
      buffer[(j + 0) * stride] = 0;
      buffer[(j + 1) * stride] = 0;
      buffer[(j + 2) * stride] = 0;
      buffer[(j + 3) * stride] = 0;
    }
  }

  long instrets = read_csr(instret) - instret_start;
  long cycles = read_csr(cycle) - cycle_start;
  long misses = read_csr(0xC04) - miss_start;
  long loads = read_csr(0xC07) - load_start;
  long stores = read_csr(0xC08) - store_start;

  printf("working_set = %2dKB, %ld instructions, %ld cycles, CPI = %f, miss rate = %f\n", 
         working_set / 1024, instrets, cycles, 
         (float) cycles / instrets, 
	 (float) misses / (loads + stores));
```

Then the output on Verilator is as follows:

```
[Verilator] Building Model
../ariane/work-ver/Variane_testharness  pk -s -p cachetest.elf
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 35573
working_set =  0KB, 110615 instructions, 143594 cycles, CPI = 1.298142, miss rate = 0.000190
working_set =  4KB, 110615 instructions, 143496 cycles, CPI = 1.297256, miss rate = 0.032940
working_set =  8KB, 110615 instructions, 149822 cycles, CPI = 1.354446, miss rate = 0.069486
working_set = 16KB, 110615 instructions, 182690 cycles, CPI = 1.651584, miss rate = 0.166680
working_set = 32KB, 110615 instructions, 294435 cycles, CPI = 2.661800, miss rate = 0.499065
working_set = 64KB, 110615 instructions, 449190 cycles, CPI = 4.060842, miss rate = 1.168497
1881046 ticks
4993895 cycles
2194498 instructions
2.28 CPI
pk completed after 20357024 cycles
```

As you can see the miss rate (of the dcache) increases as the working set becomes larger although it is strange that it becomes more than 1.

And this is what I get on the FPGA:

```
Welcome to Buildroot
buildroot login: root
login[185]: root login on 'console'
# ./cachetest.elf 
working_set =  0KB, 117173 instructions, 1123731 cycles, CPI = 9.590358, miss rate = 0.000000
working_set =  4KB, 123267 instructions, 1259001 cycles, CPI = 10.213610, miss rate = 0.000000
working_set =  8KB, 123287 instructions, 1259626 cycles, CPI = 10.217022, miss rate = 0.000000
working_set = 16KB, 123287 instructions, 1260215 cycles, CPI = 10.221800, miss rate = 0.000000
working_set = 32KB, 123329 instructions, 1260187 cycles, CPI = 10.218091, miss rate = 0.000000
working_set = 64KB, 120452 instructions, 1204221 cycles, CPI = 9.997518, miss rate = 0.000000
# 
```


This reported miss rate stays zero.

**Comment by janhoogerbrugge** [comment]
Hi,

Is anybody able to reproduce the problem that I see by running the cachetest.elf binary?

If I also print the instruction cache misses then the instruction cache behaviour looks OK:

```
working_set =  0KB, 107981 instructions, 1125843 cycles, CPI = 10.426307, ic miss rate = 835/107981, dc miss rate = 0/39787
working_set =  4KB, 107960 instructions, 1124773 cycles, CPI = 10.418424, ic miss rate = 664/107960, dc miss rate = 0/39786
working_set =  8KB, 115264 instructions, 1289737 cycles, CPI = 11.189417, ic miss rate = 1171/115264, dc miss rate = 0/42855
working_set = 16KB, 111282 instructions, 1189157 cycles, CPI = 10.685978, ic miss rate = 955/111282, dc miss rate = 0/41232
working_set = 32KB, 115239 instructions, 1290528 cycles, CPI = 11.198709, ic miss rate = 1383/115239, dc miss rate = 0/42851
working_set = 64KB, 115323 instructions, 1306216 cycles, CPI = 11.326587, ic miss rate = 1152/115323, dc miss rate = 0/42872
```

The fact that the reported data cache miss rate is zero should mean that the data cache is bypassed. The increment of the counter should come from the MISS state in miss_handler which will not be reached if miss_req_bypass/miss_req.bypass is true. Now the question is why bypass is true. For that we have to go to cache_ctrl. Bypass become true if bypass_i is true or if:

`tag_o < CACHE_START_ADDR[DCACHE_TAG_WIDTH+DCACHE_INDEX_WIDTH-1:DCACHE_INDEX_WIDTH]`

We can rule out the bypass_i input because if I remove this test then nothing changes. So then the comparison of tag_o against the caching limit is suspicious. The limit is also different between FPGA and Verilator (right?). I already replaced the compare with tag_o by:

`mshr_addr_o < CACHE_START_ADDR`

but that also does not help.
[cachetest.elf.gz](https://github.com/pulp-platform/ariane/files/2840903/cachetest.elf.gz)
 So what could be wrong with the comparison against the caching limit?

In the synthesis log I see that CACHE_START_ADDR is correctly set to 0x80000000:

`Parameter CACHE_START_ADDR bound to: -2147483648 - type: integer`

**Comment by msfschaffner** [comment]
Hi Jan, 

I believe this is a parameter propagation issue. The simulation and fpga implementation use different toplevel designs, and in the fpga top-level, the parameter `CACHE_START_ADDR` is of type `int32` instead of `logic [63:0]`. Judging from the synthesis report, Vivado then seems to propagate that constant as `int32` instead of converting to `logic [63:0]`, and hence the comparison probably always returns false in the FPGA case.

I'll upstream a patch once I could verify that this is the issue. 

Concerning the comparison: we align the cacheable region to the size of the cache ways (4kB pages in this case), and therefore we only compare with the tag.

There seems to be something "amiss" with the miss counter, I will take a look at that as well.

**Comment by jrrk** [comment]
Dear janhoogerbrugge,

This is a usefuI contribution and I think it would be a good idea to incorporate your findings into a regression suite, so that we can make progress with this issue. That way the impact of switching to a new cache or modifying the existing one will be easier to measure. However this code has no license on it at the moment, so please let me know what license you would like to use (preferably a permissive one, but it is up to you) and explicitly give your approval for this usage.

Regards,
Jonathan (from the LowRISC team)

> [cachetest.c.gz](https://github.com/pulp-platform/ariane/files/2832100/cachetest.c.gz)
> [cachetest.elf.gz](https://github.com/pulp-platform/ariane/files/2832101/cachetest.elf.gz)

**Comment by janhoogerbrugge** [comment]
Hi Jonathan,

Let's give it the same license as the rest of the Ariane code. 

Jan

**Comment by jrrk** [comment]
I ran an RTL simulation in VCS with a model of the real DDR3 memory and Xilinx controller, and the CPI is 1.3 as expected. So whatever the issue we observe on the FPGA, it cannot be blamed on the DDR3. This is on the original cache, not the OpenPiton one. Still some mystery here.

**Comment by msfschaffner** [comment]
See also https://github.com/pulp-platform/ariane-sdk/pull/11
