### ISSUE TITLE
Instruction trace when using Verilator

### ISSUE THREAD

**Issue by raulbehl** [pulp-platform/ariane#18]
Hi, 

When using Verilator for running ELFs, I see that only the performance numbers are printed on stdout. Apart from that we can dump the signals to create a .vcd file. Wanted to know if there is an option to dump the executed instruction trace as well (similar to the way we see on Questasim)? That would make debugging easier when working with Verilator. 

Thank you!

**Comment by zarubaf** [comment]
Probably something which I should add to the README.

**Comment by raulbehl** [comment]
Great. Thank you for the information. This should be helpful for now.

**Comment by ShravanSubbaraman** [comment]
You can run the verilator command using the following command to directly get the vcd file pop up in the screen : LD_LIBRARY_PATH=/home/riscv/lib/ obj_dir/Variane_wrapped --vcd=xyz.vcd -p xyz
