### ISSUE TITLE
PLIC Enhancements

### ISSUE THREAD

**Issue by zarubaf** [pulp-platform/ariane#182]
The PLIC needs some address map fixes.

**Comment by jrrk** [comment]
irq_enables_o[] has a first dimension of 1 by default, but is accessed by indexes up to 31. Should the entire address expression be modulo (%) NUM_GATEWAYS ?

**Comment by zarubaf** [comment]
I hope that the PLIC will leave this repository soon for a better implementation.

**Comment by jrrk** [comment]
I agree, just looking for a quick hack to try out my interrupt driven driver while waiting for the new PLIC to come along.

**Comment by zarubaf** [comment]
https://github.com/lowRISC/rv_plic/pull/1#issuecomment-479400990

What problems do you see with the new `plic` vs the old `plic`? I never got interrupts greater than `0` to work. So I am already positively surprised by the amount of interrupts actually arriving.

**Comment by zarubaf** [comment]
> It would be even better if Ariane had a coherent AXI DMA slave port
Is there some Linux specification to what interface the OS would expect (e.g. reusing existing drivers)? For me, that sounds like something which could be done in a student project.

**Comment by jrrk** [comment]
Most of the Linux drivers use DMA. It tends to be low-end solutions that do not. I would suggest your hypothetical student prototypes the functionality in spike and then implements the hardware to suit. I already have this prototype available: https://github.com/jrrk/riscv-isa-sim/tree/ariane
