### ISSUE TITLE
Ariane 4.1.0 release performance

### ISSUE THREAD

**Issue by jrrk** [pulp-platform/ariane#199]
The L1 is looking a lot better now, the booting is twice as quick (excluding the glacial bootrom phase).

However, a curious thing is now observed:

bare metal:

working_set = 0KB, 92207 instructions, 119933 cycles, CPI = 1.300 (now agrees with simulation)
working_set = 4KB, 92207 instructions, 129334 cycles, CPI = 1.402
working_set = 8KB, 92207 instructions, 516094 cycles, CPI = 5.597
working_set = 16KB, 92207 instructions, 516094 cycles, CPI = 5.597
working_set = 32KB, 92207 instructions, 516095 cycles, CPI = 5.597
working_set = 64KB, 92207 instructions, 516095 cycles, CPI = 5.597

all as expected.

Linux:

$ time /cachetest.elf
working_set =  0KB, 438158 instructions, 892896 cycles, CPI = 2.037840
working_set =  4KB, 436607 instructions, 880156 cycles, CPI = 2.015900
working_set =  8KB, 439825 instructions, 905571 cycles, CPI = 2.058935
working_set = 16KB, 435863 instructions, 865359 cycles, CPI = 1.985392
working_set = 32KB, 439919 instructions, 916115 cycles, CPI = 2.082463
working_set = 64KB, 435860 instructions, 875596 cycles, CPI = 2.008893
real	0m 0.45s
user	0m 0.32s
sys	0m 0.13s

which gives the conclusion that user mode under Linux is (worst case) 7.5 times slower than bare metal (?).

This implies that the combined overheads of virtual memory, timer interrupts, polling peripherals, and task switching is huge and totally swamps the expected L1 gains. 

Not in any way trying to diminish the achievement so far, but it does seem to have moved the bottleneck elsewhere. However I would expect the new PLIC to help reduce polling overheads for a start.

**Comment by msfschaffner** [comment]
Hi @jrrk,

We believe that this behavior could be due to a missing cache hierarchy / a too small L1 cache. On OpenPiton I get the following results (in user space with 8kB L1 data cache and 2x64kB shared second level cache):

```
# /cachetest.elf 
working_set =  0KB, 101400 instructions, 133934 cycles, CPI = 1.320848, ic miss rate = 37/101400, dc miss rate = 6/36898
working_set =  4KB, 104686 instructions, 155646 cycles, CPI = 1.486789, ic miss rate = 444/104686, dc miss rate = 182/38342
working_set =  8KB, 104686 instructions, 162968 cycles, CPI = 1.556732, ic miss rate = 468/104686, dc miss rate = 213/38347
working_set = 16KB, 101400 instructions, 203965 cycles, CPI = 2.011489, ic miss rate = 37/101400, dc miss rate = 8/36898
working_set = 32KB, 107972 instructions, 545040 cycles, CPI = 5.047976, ic miss rate = 868/107972, dc miss rate = 412/39790
working_set = 64KB, 112955 instructions, 1097392 cycles, CPI = 9.715302, ic miss rate = 1528/112955, dc miss rate = 961/41816
```
