### ISSUE TITLE
FPU single precision add inaccuracy

### ISSUE THREAD

**Issue by jrrk** [pulp-platform/ariane#233]
I am testing the improved, pipelined FPU under ariane-dev branch. I am trying to run TestFloat and in the main it works well, but I am having problems with certain particular operands, as per the attached testcase:

  TEST_FP_OP2_S_( 2, fadd.s,             33354290,             33357822,   -3531
.952392578125 ); #   actually returns  33357822
  TEST_FP_OP2_S_( 3, fadd.s, -1.701411733192644E+38, -1.701411733192644E+38, -2.
350970765024232E-38 ); #  actually returns NAN

[rv64uf-p-custom.zip](https://github.com/pulp-platform/ariane/files/3137711/rv64uf-p-custom.zip)

I can add more test vectors later if needed

**Comment by msfschaffner** [comment]
Hi Jonathan, thanks for testing! I'm forwarding this one to @stmach who designed the FPU. Steve, could you take a look?

**Comment by jrrk** [comment]
Postscript: I have found that the FPGA does not always produce consistent results. Perhaps there is a problem with saving and restoring the FPU state during a context switch ?

**Comment by jrrk** [comment]
We have a workaround [here](https://github.com/lowRISC/linux/pull/1)

**Comment by zarubaf** [comment]
Thanks for bisecting this bug.  I will go through the state dirtying code to see which instructions might be missing.

**Comment by zarubaf** [comment]
That is indeed stupid and a mistake. Instead of the `0` it should be `i`.

**Comment by jrrk** [comment]
Unfortunately that doesn't seem to help either. Perhaps there are some calculations in progress that don't get saved when the co-processor status is saved ? Perhaps you could suggest some signals to look at in the internal logic analyzer ?

**Comment by jrrk** [comment]
@zarubaf I think I found the problem, see associated pull request [here](https://github.com/pulp-platform/ariane/pull/240)
