### ISSUE TITLE
Is it possible to use jlink for debugging?

### ISSUE THREAD

**Issue by hyf6661669** [pulp-platform/ariane#250]
At present I only have a JLINK V9. I want to use the USB-JTAG interface on GENESYS2 board for observing  waves in ILA of Vivado, while debugging the application codes. Since buying a new "Olimex Ltd. ARM-USB-OCD-H" is too expensive, it would be very nice if you can give some information on debugging by using JLINK.
Thanks.

**Comment by zarubaf** [comment]
Theoretically, that should “just work” if it is supported by OpenOCD. You need to adapt the transport mode in the OpenOCD script.
