### ISSUE TITLE
csr_we & exception

### ISSUE THREAD

**Issue by suppamax** [pulp-platform/ariane#252]
Hi,

I have the following scenario
U-mode => exception => exception handler in S-mode (starts with "csrrw t0, sscratch, t0") => interrupt => M-mode => back to S-mode exception handler
The csrrw instruction is executed twice: once every time the program goes in S-mode, because the epc value is in both cases set to the beginning of the Smode exception handler.
This results in a corrupted t0 and sscratch once the S trap handler continues.

I noticed that csr operations are not disabled when ex_i.valid=1.
This behaviour seem also to be different from what happens with the normal registers: write operations are filtered out in case of exceptions.

What's the reason for that?
Do you think this might be a problem in Ariane?

This has been noticed using version bsc-3-10-18.

Regards,
Max

**Comment by msfschaffner** [comment]
Hi @suppamax,

`bsc-3-10-18` is a really outdated version - we have fixed many bugs and improved the performance of the core in the meantime. I hence highly recommend to switch to the upcoming `v4.2` release and try again (we are going to release later today). This might solve your problem.

Best,
Michael
