### ISSUE TITLE
Verilator broken

### ISSUE THREAD

**Issue by wallento** [pulp-platform/ariane#259]
Upstream verilator is broken with updates after 4.014. I am pretty sure it is a verilator issue, but just want to track the problem here too.

Created issue at verilator: https://www.veripool.org/issues/1456-Verilator-Internal-error-after-4-014

**Comment by zarubaf** [comment]
Looks like they provided a fix already.

**Comment by zarubaf** [comment]
Thanks for letting us know!

**Comment by wallento** [comment]
Yes, I think it is fixed, but I didn't find time yet to check. Will do soon and close the issue.
