### ISSUE TITLE
Error in SCP files from the host 

### ISSUE THREAD

**Issue by JunnanLi** [pulp-platform/ariane#281]
Hi,
@zarubaf 
I meet an error when using "scp" command to copy files from the host to the arianed-based linux runing on FPGA: it is down. Is there any other way to copy files?

**Comment by zarubaf** [comment]
You can format the second partition on the sdcard and mount it.

**Comment by JunnanLi** [comment]
Thank you very much, it works!

**Comment by JunnanLi** [comment]
@zarubaf 
Hi,  
Have you ever encountered the above problem (the linxu is down when using scp command), and where the problem is? If the problem lies in the driver of network interface, We are happy to help to patch it.
