### ISSUE TITLE
Is there any result data (fmax, utilization, etc.) for the implementaion of soc on the Genesys 2 board

### ISSUE THREAD

**Issue by mathmax12** [pulp-platform/ariane#283]
Is there any result data (fmax, utilization, etc.) for the implementation of soc on the Genesys 2 board?
Thanks.

**Comment by zarubaf** [comment]
You get utilization and timing reports when running the implementation. A nice table for the reader would be welcome as a PR. For Ariane Details you can have a look at our CARV submission (https://carrv.github.io/2019/papers/carrv2019_paper_12.pdf).
