### ISSUE TITLE
How to use GPIO pins?

### ISSUE THREAD

**Issue by JunnanLi** [pulp-platform/ariane#289]
I found that the FTDI chip exposes a second serial link that is routed to GPIO pins on the FPGA  (RISC-V debug module). And if we want to add a self-defined register, do we need to modify the code in the software (FTDI driver)? I hope that you can briefly explain how it works.

**Comment by zarubaf** [comment]
I am not sure what a `self-defined` register should be. There are plenty of resources regarding the FTDI chips like [libftdi](https://www.intra2net.com/en/developer/libftdi/index.php). Maybe you can even use OpenOCD to do what you want if you dig through the manual.
