### ISSUE TITLE
ASIDLEN

### ISSUE THREAD

**Issue by suppamax** [pulp-platform/ariane#291]
Hi,
I see that ASIDLEN is set to 1 via ASID_WIDTH. So only 2 ASID values are possible.

Would it be possible to configure it to a different value? Has it ever been tested?

Thanks,
Max

**Comment by hyf6661669** [comment]
It seems that ASID is not used by software.

**Comment by axel-h** [comment]
ASIDs are used by a micro kernel OS, they are an important thing for performance optimization.

**Comment by zarubaf** [comment]
Theoretically ASIDs are provisioned but this feature has never been tested nor is the selective flushing logic implemented, mainly because the current Linux distribution doesn't use different ASID widths.
