### ISSUE TITLE
Is there a list of compatible linux image for the Ariane

### ISSUE THREAD

**Issue by mathmax12** [pulp-platform/ariane#293]
Hi,
I just start with the Ariane.
1. I notice that in the link https://github.com/pulp-platform/ariane-sdk#linux  it says
"You can also build a compatible linux image with bbl that boots linux on the ariane fpga mapping:
$ make vmlinux # make only the vmlinux image"

Is there a list for the compatible linux image?

2. Does it support the NVMe driver?

Thanks.

**Comment by Moschn** [comment]
We use the mainline linux kernel. I am not sure what the current version in the ariane-sdk repository is, but previously we booted with 4.19/4.20. The kernel obviously needs to be built with a RISC-V cross-compilation toolchain and it needs a bootloader first (we are using bbl for the moment).

As for NVMe, I guess you would need a NVMe peripheral first (which probably also needs a PCI bus).

**Comment by mathmax12** [comment]
Thanks very much for the reply.
