### ISSUE TITLE
verilator:not found

### ISSUE THREAD

**Issue by mathmax12** [pulp-platform/ariane#295]
Hi,
I followed the readme file.
Installed the RISC-V tools.
Checked the update of Ariane by using(git submodule update --init --recursive)
When I try "make verilate" the system throw:
"/bin/sh: 1: verilator: not found
[Verilator] Building Model
....
...
bin/sh: 1: verilator: not found
Makefile:378: recipe for target 'verilate' failed
make: *** [verilate] Error 127
"

Can anybody help me with this?

**Comment by Moschn** [comment]
Verilator is not included in the ariane-sdk. It only includes the toolchain and the linux image. You can get verilator from here: https://www.veripool.org/wiki/verilator.

Take a look at our verilator CI [script](ci/install-verilator.sh) for an example on how to install verilator.

**Comment by mathmax12** [comment]
Thanks. it works after I installed the verilator.
