### ISSUE TITLE
Linux boot get stuck

### ISSUE THREAD

**Issue by mathmax12** [pulp-platform/ariane#309]
Hi,
The pre-built linux image Ariane 4.2 on the Genesys2 board.
Then I followed the Ariane-SDK (https://github.com/pulp-platform/ariane-sdk/issues?q=is%3Aissue+is%3Aclosed) generate bootloarder and linux image.

Each time the system booting will get stuck at "mmcblk0: mmc0:0000 SC16G 14.8 GiB" (Below is the booting information).
Is there any differece betweeen Ariane 4.2 and Ariane-SDK?

/**********
Hello World!
init SPI
status: 0x0000000000000025
status: 0x0000000000000025
SPI initialized!
initializing SD...
SD command cmd0         response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 01
SD command cmd55        response : 01
SD command cmd41        response : 00
sd initialized!
gpt partition table header:
        signature:      5452415020494645
        revision:       00010000
        size:           0000005C
        crc_header:     86AE3791
        reserved:       00000000
        current lba:    0000000000000001
        backup lda:     0000000001DACBFF
        partition entries lba:          0000000000000002
        number partition entries:       00000080
        size partition entries:         00000080
gpt partition entry 00
        partition type guid:    D5F7127456A1134B81DC867174929325
        partition guid:         F9B4DB0EBFFDF04895C342715347205D
        first lba:      0000000000000800
        last lba:       00000000000107FF
        attributes:     0000000000000000
        name:   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
gpt partition entry 01
        partition type guid:    AF3DC60F838472478E793D69D8477DE4
        partition guid:         A59F785445B255459303E63C7EADD23B
        first lba:      0000000000010800
        last lba:       0000000001DACBDE
        attributes:     0000000000000000
        name:   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
gpt partition entry 02
        partition type guid:    00000000000000000000000000000000
        partition guid:         00000000000000000000000000000000
        first lba:      0000000000000000
        last lba:       0000000000000000
        attributes:     0000000000000000
        name:   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
gpt partition entry 03
        partition type guid:    00000000000000000000000000000000
        partition guid:         00000000000000000000000000000000
        first lba:      0000000000000000
        last lba:       0000000000000000
        attributes:     0000000000000000
        name:   000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
copying boot image ................................ done!
[    0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[    0.000000] Linux version 5.1.0-rc7 (root@msl-mip-dev18) (gcc version 8.2.0 (GCC)) #4 SMP Wed Aug 21 14:53:07 PDT 2019
[    0.000000] initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   DMA32    [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000000bfffffff]
[    0.000000] software IO TLB: mapped [mem 0xbb1fd000-0xbf1fd000] (64MB)
[    0.000000] elf_hwcap is 0x112d
[    0.000000] percpu: Embedded 15 pages/cpu s24280 r8192 d28968 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 258055
[    0.000000] Kernel command line: earlyprintk
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.000000] Sorting __ex_table...
[    0.000000] Memory: 952764K/1046528K available (3709K kernel code, 230K rwdata, 1046K rodata, 6091K init, 797K bss, 93764K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 0, nr_irqs: 0, preallocated irqs: 0
[    0.000000] plic: mapped 3 interrupts with 1 handlers for 2 contexts.
[    0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [0]
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x6eb3e4560, max_idle_ns: 881590406254 ns
[    0.000331] sched_clock: 64 bits at 15MHz, resolution 66ns, wraps every 4398046511080ns
[    0.046895] printk: console [hvc0] enabled
[    0.049107] Calibrating delay loop (skipped), value calculated using timer frequency.. 30.00 BogoMIPS (lpj=150000)
[    0.051999] pid_max: default: 32768 minimum: 301
[    0.063624] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.067494] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.097656] *** VALIDATE proc ***
[    0.150287] rcu: Hierarchical SRCU implementation.
[    0.179427] smp: Bringing up secondary CPUs ...
[    0.181029] smp: Brought up 1 node, 1 CPU
[    0.203768] devtmpfs: initialized
[    0.261576] random: get_random_bytes called from setup_net+0x32/0x15c with crng_init=0
[    0.271203] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.274218] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.298049] NET: Registered protocol family 16
[    0.728301] usbcore: registered new interface driver usbfs
[    0.733641] usbcore: registered new interface driver hub
[    0.738255] usbcore: registered new device driver usb
[    0.781539] clocksource: Switched to clocksource riscv_clocksource
[    0.850327] NET: Registered protocol family 2
[    0.885663] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes)
[    0.888791] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    0.896813] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[    0.907161] TCP: Hash tables configured (established 8192 bind 8192)
[    0.921517] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.924694] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.935351] NET: Registered protocol family 1
[    0.971863] RPC: Registered named UNIX socket transport module.
[    0.973722] RPC: Registered udp transport module.
[    0.975057] RPC: Registered tcp transport module.
[    0.976379] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   19.885864] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[   20.488125] NFS: Registering the id_resolver key type
[   20.490396] Key type id_resolver registered
[   20.492837] Key type id_legacy registered
[   20.494569] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[   20.966062] io scheduler mq-deadline registered
[   20.967644] io scheduler kyber registered
[   24.082790] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[   24.157852] 10000000.uart: ttyS0 at MMIO 0x10000000 (irq = 1, base_baud = 3125000) is a TI16750
[   25.010031] printk: console [ttyS0] enabled
[   25.079376] xilinx_spi 20000000.xps-spi: at 0x20000000 mapped to 0x(____ptrval____), irq=2
[   25.119963] libphy: Fixed MDIO Bus: probed
[   25.148737] lowrisc-digilent-ethernet: Lowrisc ethernet platform (30000000-30007FFF) mapped to ffffffd004028000
[   25.203203] libphy: GPIO Bitbanged LowRISC: probed
[   25.214430] Probing lowrisc-0:01 (address 1)
[   25.229397] RTL8211E Gigabit Ethernet lowrisc-0:01: attached PHY driver [RTL8211E Gigabit Ethernet] (mii_bus:phy_addr=lowrisc-0:01, irq=POLL)
[   25.281512] lowrisc-eth 30000000.lowrisc-eth: Lowrisc Ether100MHz registered
[   25.303639] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[   25.374787] mmc_spi spi0.0: SD/MMC host mmc0, no WP, no poweroff, cd polling
[   25.404193] usbcore: registered new interface driver usbhid
[   25.416370] usbhid: USB HID core driver
[   25.478670] NET: Registered protocol family 10
[   25.562892] Segment Routing with IPv6
[   25.575240] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[   25.622110] NET: Registered protocol family 17
[   25.659119] Key type dns_resolver registered
[   26.187830] Freeing unused kernel memory: 6088K
[   26.197912] This architecture does not have kernel memory protection.
[   26.211728] Run /init as init process
[   26.278820] mmc0: host does not support reading read-only switch, assuming write-enable
[   26.296543] mmc0: new SDHC card on SPI
[   26.380244] mmcblk0: mmc0:0000 SC16G 14.8 GiB

**Comment by zarubaf** [comment]
Are you still facing that issue? My initial guess would be that the spi block device driver is somehow broken. Does it consistently not boot?

**Comment by mathmax12** [comment]
Yes.
If the FPGA bitstream keeps the same, using the pre-build Linux image Ariane 4.2  will work. 
My own build with the Ariane-SDK doesn't work.

This problem persists. Here are some details that I found https://github.com/pulp-platform/ariane-sdk/issues/23#issuecomment-525485651
But still wouldn't work.
