### ISSUE TITLE
Memory preloading not working

### ISSUE THREAD

**Issue by gpersyn** [pulp-platform/ariane#314]
Howdy,

When I use the command "make sim preload=elf" for a hello world elf file the simulation gets stuck and never finishes executing the program. Has anyone gotten this feature working?

**Comment by zarubaf** [comment]
Pre-loading does currently not support simulation termination/communication with the proxy kernel.  Proxy kernel needs to be aware of the `tohost` location which it reads when loading the elf via the debug module and currently (or at least the last time I looked) you couldn't switch-off the loading the elf via the debug module. The only usecase for preloading for me so far was to boot the Linux kernel on simulation which doesn't terminate.
