### ISSUE TITLE
Error when SCP files from the host

### ISSUE THREAD

**Issue by JunnanLi** [pulp-platform/ariane#316]
Hi,

Have you ever encountered an error (linux is down) when using SCP commond to copy files from the host? Furthermore, we use the "scp -v" to track the scp process, and find that the problem occurs after "debug1: fd 0 clearing O_NONBLOCK".

**Comment by zarubaf** [comment]
I never did, but I do not use scp often.

**Comment by JunnanLi** [comment]
Thank you very much. 
After formating SD cart to EXT2, the problem has been solved.
