### ISSUE TITLE
Return-address stack prediction hints

### ISSUE THREAD

**Issue by suppamax** [pulp-platform/ariane#322]
Could you please comment on this change request?
https://github.com/pulp-platform/ariane/pull/318/files

Looking at table 2.1 in the user level specs v2.2 a return (pop) should happen when rs1=(x1 or x5) and rd != rs1, but in your code
`((instr_i[11:7] == 5'd1) | instr_i[11:7] == 5'd5)`
seems like you're using rd=(x1 or x5) instead, being rd = instr[11:7] according to the specs.

**Comment by zarubaf** [comment]
Thanks. Indeed that seemed to be incorrect.
