### ISSUE TITLE
Frequency in ASIC?

### ISSUE THREAD

**Issue by hyf6661669** [pulp-platform/ariane#323]
Could you tell any information about the frequency that Ariane could get in ASIC implementation?
Much thanks.

**Comment by hyf6661669** [comment]
I found your paper here:

https://ieeexplore.ieee.org/document/8777130
https://arxiv.org/pdf/1904.05442.pdf

Excellent work!

**Comment by hyf6661669** [comment]
@zarubaf  
Could you tell me that 1.7GHz is reached with or without RV64FD ?

![image](https://user-images.githubusercontent.com/18757974/65737640-aaef1680-e111-11e9-813e-cc832bf01bf1.png)

**Comment by zarubaf** [comment]
Thanks. The reported 1.7 GHz were without F and D. The silicon measurements are from an earlier tape-out which didn't support the floating point extension. It will most probably be a bit slower with the FPU although the FPU can be flexibly pipelined to suit your area/timing/latency requirements.

**Comment by polkeemfungible** [comment]
Hi, are there any examples of how to pipeline the FPU and find those registers to specify to synthesis scripts for register retiming?

**Comment by Moschn** [comment]
The [fpu repository](https://github.com/pulp-platform/fpnew) contains documentation on how to pipeline the FPU:

https://github.com/pulp-platform/fpnew/blob/master/docs/README.md#implementation---implementation-options

https://github.com/pulp-platform/fpnew/blob/master/docs/README.md#pipeconfig---pipeline-register-placement

https://github.com/pulp-platform/fpnew/blob/master/docs/README.md#pipelining
