### ISSUE TITLE
Should riscv-isa-sim be a submodule?

### ISSUE THREAD

**Issue by jimmysitu** [pulp-platform/ariane#329]
Hi, All

There is a copy of Spike source code under ariane/tb/riscv-isa-sim. Is it a fork of [riscv/riscv-isa-sim](https://github.com/riscv/riscv-isa-sim)? Should it be a submodule of ariane?

**Comment by zarubaf** [comment]
No, its heavily modified and only used in Ariane. For my taste we already have too many submodules anyway.
