### ISSUE TITLE
Implementation of FENCE instruction

### ISSUE THREAD

**Issue by hyf6661669** [pulp-platform/ariane#339]
I find that FENCE instruction in Ariane will invalidate every set of dcache and write back the cacheline which is dirty. In https://github.com/riscv/riscv-isa-manual/issues/252, it is said that flushing the whole dcache is not necessary. I also think that flushing the whole dcache is too costly. Do you have any suggestion about a more effective implementation for FENCE isntruction?

**Comment by zarubaf** [comment]
I do not understand what you want to communicate here. Whether a cache flush is necessary is an architectural choice:
a. For the write-through cache, the cache will not be flushed. We flush the write-buffer, the invalidation will be handled by OpenPiton's cache coherency protocol.
b. For the write-back cache, there is no other choice without cache coherency.
Go implement a cache coherency protocl, then you can enforce a global memory ordering. This will make the `FENCE` instruction more "effective".
