### ISSUE TITLE
Query regading Multithread support of Ariane

### ISSUE THREAD

**Issue by h-soni** [pulp-platform/ariane#346]
According to the slide "https://carrv.github.io/2019/slides/carrv2019_slides_12.pdf" it gives us an impression that openpiton+Ariane has not supported Multithread whereas in Github Documentation of ariane they have added "ariane-multi-hart.cfg" and "ariane.cfg"  5 months ago which gives us an impression that it Ariane supports multithreading.
 

Please give me a clearity that whether anyone  ( of Ariane and Ariane+piton) supports multi_threading or not ?

**Comment by zarubaf** [comment]
Ariane does not implement multi-threading. The `multi-hart` is the configuration to debug multi core systems. Multi-threading is an implementation decision, RISC-V doesn’t care how you implement multiple threads.
