### ISSUE TITLE
where is add_sources.tcl

### ISSUE THREAD

**Issue by salmansheikh** [pulp-platform/ariane#363]
While trying to make this for the VC707, I hit this error, where there is no add_sources.tcl file.   

 read_ip xilinx/xlnx_axi_quad_spi/ip/xlnx_axi_quad_spi.xci
 read_ip xilinx/xlnx_clk_gen/ip/xlnx_clk_gen.xci
set_property include_dirs { "src/axi_sd_bridge/include" "../src/common_cells/include" } [current_fileset]
 source scripts/add_sources.tcl
couldn't read file "scripts/add_sources.tcl": no such file or directory
    while executing
"source scripts/add_sources.tcl"
    (file "scripts/run.tcl" line 39)
INFO: [Common 17-206] Exiting Vivado at Mon Dec 16 17:22:09 2019...
Makefile:25: recipe for target 'work-fpga/ariane_xilinx.bit' failed
make: *** [work-fpga/ariane_xilinx.bit] Error 1

**Comment by zarubaf** [comment]
`add_sources.tcl` should be generated by the Make target:
https://github.com/pulp-platform/ariane/blob/f13f6d4371975dd0148a7db7e0c766f74ce36b2e/Makefile#L518
