### ISSUE TITLE
Flush signal in PTW

### ISSUE THREAD

**Issue by zhaoxiahust** [pulp-platform/ariane#384]
Hi guys, 

  If we have the flush_i signal valid, why cannot we set state_d=IDLE directly? Why do we need the WAIT_RVALID state?
  I read [issue61](https://github.com/pulp-platform/ariane/issues/61) which mentions that without checking we will have an error. However, I still cannot understand how this violates the req, gnt protocol.
  Any comments about this? An example will help a lot!!

Cheers,
Xia

**Comment by zhaoxiahust** [comment]
I understand the problem now to some degree. There is an outstanding access from PTW in Dcache. You cannot directly jump to the idle state as the useless access can come back in the future.

**Comment by zarubaf** [comment]
Yes exactly!
