### ISSUE TITLE
Make verilator 

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/ariane#4]
Hi, I am getting the following issue while running "make verilate" command:
![image](https://user-images.githubusercontent.com/36438648/36194620-b00eb9ea-116a-11e8-81a6-bd54dcd8cdfe.png)

**Comment by zarubaf** [comment]
This is because your `riscv-fesvr` installation is not in your compiler's/linker's path. Also note that for the moment Ariane requires our forked version of `riscv-fesvr` (which can be found  [here](https://github.com/pulp-platform/riscv-fesvr)).

**Comment by lfernand4** [comment]
I install "riscv-fesvr" in an other directory. How can I add it to my Path ?

**Comment by zarubaf** [comment]
As with any other library you don't have in your default path. 
```
export LIBRARY_PATH=$LIBRARY_PATH:/fesvr/installation/lib
export LD_LIBRARY_PATH=$LIBRARY_PATH:/fesvr/installation/lib
export C_INCLUDE_PATH=$LIBRARY_PATH:/fesvr/installation/include
export CPLUS_INCLUDE_PATH=$LIBRARY_PATH:/fesvr/installation/include
```
You might want to put this into your shell's start-up script.

**Comment by lfernand4** [comment]
Thank you for your help.
I have a new error whith the make verilate : 
![image](https://user-images.githubusercontent.com/36438648/36313313-6fc33f46-1331-11e8-8aba-ac6c1125842c.png)

**Comment by zarubaf** [comment]
It seems you are using the official version and not our fork, which I linked in the previous message. 

> Also note that for the moment Ariane requires our forked version of `riscv-fesvr` (which can be found  [here](https://github.com/pulp-platform/riscv-fesvr)). 

You can use our version with the rest of the RISC-V ecosystem though. The changes are the visibility of the two variables (which is the error you get ;-))

**Comment by lfernand4** [comment]
This Path is for the fork : /prj/xpuips/riscv/riscv-fesvr/include
We can see that it use the good path.

**Comment by lfernand4** [comment]
I think that the path is good. 
/prj/xpuips/riscv/riscv-fesvr/ is the good path.

**Comment by zarubaf** [comment]
Yes, you are right - thanks for reporting. The changes were on a branch (`expose-htif`). Can you try to checkout the newest changes from `pulp-platform/riscv-fesvr` and rebuild it?

**Comment by lfernand4** [comment]
It work ! Nice

**Comment by lfernand4** [comment]
New problem : 
![image](https://user-images.githubusercontent.com/36438648/36367339-825b114c-1552-11e8-8542-3b59def6ceba.png)
It is because my riscv-fesvr installation is not in my compiler's/linker's path ?

**Comment by lfernand4** [comment]
Now I want to run dhrystone. I have the riscv-tests. But i don’t know how to configure the good ISA.

This work : 
Variane_wrapped -p /prj/xpuips/riscv/riscv-tests/benchmarks/dhrystone.riscv

Can you help me ?

**Comment by zarubaf** [comment]
So theoretically this should work. Takes a couple of seconds though ;-) Are you experiencing any issues?

Also note that there is a branch on which I am working right now which significantly improves the IPC (Drystone ~1.71).

**Comment by lfernand4** [comment]
The problem is I found 1.19. I think i'am making a mistake. I don't configure the ISA.

**Comment by zarubaf** [comment]
Im afraid I can't really follow. Everything should be compatible to the latest RISC-V compiler and RISCV-tests (at least one week ago ;-)). You can't really tweak the uArch but only the compiler.

**Comment by lfernand4** [comment]
ok

**Comment by lfernand4** [comment]
In the makefile from : riscv-tests/benchmarks. I don't found where the -march is configure for the compiler. That's why I think the drystone results are incoherent.

**Comment by zarubaf** [comment]
Yes the benchmarks get compiled with the full compiler functionality. But nevertheless, Dhrystone doesn't use either floating points nor atomics. So it should work out of the box.

**Comment by lfernand4** [comment]
When I run dhrystone out of the box I found : 
![image](https://user-images.githubusercontent.com/36438648/36781363-f6f8b174-1c75-11e8-92e5-dea7b0a9c457.png)
It is correct ? and how to convert in Dhrystones/MHz ? (500 runs and Hz = 1.000.000)
It is : (HZ * Number_Of_Runs) / (1757*mcycle) ?

**Comment by zarubaf** [comment]
That looks like the supposed outcome. That being said it seems that the Dhrystone report can't be taken as an absolute value ([see this thread](https://groups.google.com/a/groups.riscv.org/forum/#!topic/sw-dev/b2eTdNOtjhA)). You can use it though to compare to Rocket for example.

**Comment by lfernand4** [comment]
What do you use to run Dhrystone ? riscv-tests ?

**Comment by zarubaf** [comment]
At the moment yes, just for relative comparisons though.

**Comment by Nicu1309** [comment]
Hello, I am trying to run the "make verilate" command, but I am getting several syntax errors. I guess this could be related to the verilator version that I am using (Verilator 3.874). Could you please confirm?

![screeshot](https://user-images.githubusercontent.com/14819538/38723980-20e3db80-3f03-11e8-9459-959328894343.png)

Thanks :)

**Comment by Nicu1309** [comment]
Hey @raulbehl, 
perfect, I got it built with Verilator 9.20. Thanks a lot 😃
