### ISSUE TITLE
command: make sim 

### ISSUE THREAD

**Issue by Yi1101** [pulp-platform/ariane#401]
when run the following command:
>make sim elf-bin=$RISCV/riscv64-unknown-elf/bin/pk target-options=hello.elf
The QuestaSim opens and keeps runing. But how could I know that all the instructions are retired？and when the test is finished? and when the Questasim should stop? How could I know these information?
Looking forward to your reply!

**Comment by zarubaf** [comment]
Once `hello.elf` finishes (assuming it does). It will return control to `pk` and `pk` will tell the testbench to finish, which will then tell QuestaSim to finish. So everything should be automatic.
