### ISSUE TITLE
Silicon Implementation Constraint File

### ISSUE THREAD

**Issue by Yi1101** [pulp-platform/ariane#403]
Dear Author,
When implemented your design, I encounted the following two problems. Really looking forward to your reply, thank you in advance!
Question 1:
The platform provides the xdc (such as genesys-2.xdc) for FPGA implementation. It doesn't provide the constraint file for silicon implementation, isn't it ? Will you provide it in the future?
Question 2:
ariane_testharness as the top file of the DUT, why does it only have 4 signals (clk_i, rtc_i, rst_ni, exit_o) as input/output ? May I have the reason for the design of the top level ?

**Comment by zarubaf** [comment]
Afaik we, unfortunately, can't provide the ASIC constraint files. In any case: Ariane is just a synchronous design so no special considerations are needed. For the SoC, as we provide it in this repository we never taped-out the exact same configuration so we don't have any ASIC constraint file.
