### ISSUE TITLE
JTAG trst_n pin

### ISSUE THREAD

**Issue by RaphaelKlink** [pulp-platform/ariane#404]
In the Config files for the OpenOCD, you explicit add the trst_n pin.
Is this pin necessary for the ariane debugging via OpenOCD, or can it be hardwird to 1 to deactivate it?

**Comment by zarubaf** [comment]
Well, `trst_n` is used in the debug module. But JTAG specifies that you can always use the protocol to perform a reset. So I guess its "technically" not necessary.
