### ISSUE TITLE
mibench and linux

### ISSUE THREAD

**Issue by Liyang131313** [pulp-platform/ariane#42]
Excuse me，I would like to ask a question about ariane

Is it possible to run linux on ariane now, can I use MiBenc to test ariane?

Thanks, wish all the best.

**Comment by zarubaf** [comment]
It is possible to run Linux on Ariane. But:
- In RTL simulation you will wait ~1.5 days for it to boot.
- For the FPGA I am currently not providing open-source infrastructure.
So, while theoretically it is possible, it will require a lot of work right now.

**Comment by gurkaynak** [comment]
Just to clarify, we want to also release the FPGA infrastructure for Ariane as open source, and it will happen sooner than later. But at the moment, it is not really ready for release.
