### ISSUE TITLE
Unable to run User-Space applications

### ISSUE THREAD

**Issue by SpaceNitro** [pulp-platform/ariane#424]
Hello,

When I follow the steps to run "User-Space applications" from Ariane directory, I get the error : ../configure : no file or directory 
when I try to use this command : ../configure --prefix=$RISCV --host=riscv64-unknown-elf
![image](https://user-images.githubusercontent.com/46192993/81284335-44928500-905e-11ea-880e-a922aa40a2fb.png)

Riscv-gnu toolchain, riscv-tools, verilator are installed.

Could you help me to solve this error ? 
Thank you for your time and consideration.

**Comment by zarubaf** [comment]
That step should be done in `riscv-pk` not in the build folder of Ariane.

**Comment by zarubaf** [comment]
Once you have `pk` installed in your RISC-V install dir you can use it to run user-space applications.

**Comment by SpaceNitro** [comment]
Hello, 
Thank you for your answer.

I installed riscv-pk in the install directory. But when I try to run the make file, I get an error :
![image](https://user-images.githubusercontent.com/46192993/83243453-3556b100-a19e-11ea-88d1-7b5fd046a523.png)
![image](https://user-images.githubusercontent.com/46192993/83243535-53241600-a19e-11ea-8a6a-c58919f28a97.png)

What is wrong with my installation?
Thank you.

**Comment by zarubaf** [comment]
I was running into a similar issue on some machines. The problem is that the `Makefile` tries to use your system (x86) `gcc` to compile a RISC-V binary. You can solve the issue by specifying which compiler to use:
```
make CC=riscv64-unknown-elf-gcc
```

That should solve the issue.

**Comment by SpaceNitro** [comment]
I tried `make CC=riscv64-unknown-elf-gcc` but it is not working. 
![image](https://user-images.githubusercontent.com/46192993/83267730-ef611380-a1c4-11ea-865c-b1c82cf6fb52.png)
![image](https://user-images.githubusercontent.com/46192993/83267809-0b64b500-a1c5-11ea-86d4-6b7937b98238.png)

I think the compiler doesn't know where to find `riscv64-unknown-elf-gcc`.
checking for riscv64-unknown-elf-g++... no
checking for riscv64-unknown-elf-c++... no
checking for riscv64-unknown-elf-gpp... no
checking for riscv64-unknown-elf-aCC... no
checking for riscv64-unknown-elf-CC... no
checking for riscv64-unknown-elf-cxx... no
checking for riscv64-unknown-elf-cc++... no
checking for riscv64-unknown-elf-cl.exe... no
checking for riscv64-unknown-elf-FCC... no
checking for riscv64-unknown-elf-KCC... no
checking for riscv64-unknown-elf-RCC... no
checking for riscv64-unknown-elf-xlC_r... no
checking for riscv64-unknown-elf-xlC... no

What is wrong with my riscv64 gcc elf?

**Comment by SpaceNitro** [comment]
I managed to solve my problem. My `PATH` variable was not redirected to the bin directory where we can find riscv-unknow-elf-gcc file for example. Thank you for the help.
