### ISSUE TITLE
core pause after debug relase in gdb

### ISSUE THREAD

**Issue by RaphaelKlink** [pulp-platform/ariane#432]
Hello,

When i debug the core on an fpga via gdb there is a pause of 250 cycles after the core is released from the debug state, where it does not do anything.

Can some one explain what the core or the whole soc does during this time.
Thank you for your help

![2020-05-30 210825](https://user-images.githubusercontent.com/28709534/83337400-3cbfac80-a2bb-11ea-8d88-b426149759fb.png)

**Comment by zarubaf** [comment]
I am pretty sure that is a `fence[.i]` instruction which steps through the cache and invalidates its entries. You can check the controller signals which orchestrates the flushing.
