### ISSUE TITLE
Cannot launch OS with the std cache

### ISSUE THREAD

**Issue by zhaoxiahust** [pulp-platform/ariane#437]
Hi guys,

  I am trying to use std_cache in the FPGA platform by compiling the project (make fpga) without the "WT_DCACHE". However, the system stuck after printing "sd initialized!". 
  
  The interesting part is that if I disable caching the memory space from 0x83ffe000 to 0x84000000 which is 8KB size, the bootloader and OS can be launched successfully. Based on startup.S file in fpga\src\bootrom, 0x84000000 is the stack pointer address. It seems to me that the stack space cannot be cached when the Bootrom works, right? What caused this?

  I totally understand that the std cache is not used now but I think it is still interesting to figure out the reason behind it. Any comments are welcome.

Cheers,
Xia

**Comment by zarubaf** [comment]
I agree. Unfortunately, the write-back cash is a bit buggy at the moment. I think there is some strong intention on getting it to work within the group in the next three months. Sorry for not having better news 😔
