### ISSUE TITLE
failling to run ariane tandem

### ISSUE THREAD

**Issue by suhasskrishanmurthy** [pulp-platform/ariane#438]
Hi,
I am trying to run ariane tandem, but it is saying there should be some header files in a directory called ./tb/riscv-isa-sim/install/include/spike . I dont  have ./tb/riscv-isa-sim/install directory.
Is this to be created by me or it will be created by script travis-ci-emul.sh .
Please help
my command was,
make sim spike-tandem=1 preload=./tmp/riscv-tests/benchmarks/dhrystone.riscv batch-mode=1

**Comment by zarubaf** [comment]
Unfortunately the tandem simulation is an unsupported feature at the moment. That directory would need to be populated with the spike installation of this repository‘s spike.
