### ISSUE TITLE
synchronizer for ariane_verilog_wrap

### ISSUE THREAD

**Issue by Kbz6** [pulp-platform/ariane#443]
Hello,

I want to instantiate ariane_verilog_wrap to test some features of ariane core alone.

However, I can't find the "synchronizer" modules in the source files.

Thanks

![image](https://user-images.githubusercontent.com/62616187/84125951-92275680-aa3d-11ea-94c4-52b4bbe18ae1.png)

**Comment by zarubaf** [comment]
`ariane_verilog_wrap` is solely used by the OpenPiton module. Hence you will find the missing module there. You should be able to synthesize the SV top stand-alone as well, we do not use any interfaces.
