### ISSUE TITLE
vsim-5 error

### ISSUE THREAD

**Issue by mansijain1234** [pulp-platform/ariane#46]
When I am doing run -all command in vsim, I am getting this error.
![image](https://user-images.githubusercontent.com/39843284/40866111-423d5202-65b9-11e8-8cd1-4fd2d495a579.png)

Can anyone help me with this?

**Comment by mansijain1234** [comment]
Hello,

Actually we were facing this issue when we were trying to run C program with printf and return statements. I think it is because Questa is not linked to fesvr

Thank you,
Mansi

**Comment by raulbehl** [comment]
Yes, that is correct. :)

**Comment by mansijain1234** [comment]
And one more thing, did you run the CoreMark benchmark on ariane?

**Comment by raulbehl** [comment]
No, I haven't got a chance to run much on Ariane lately. I have been busy with some personal work and hoping to get back to speed soon.

**Comment by mansijain1234** [comment]
Hello,

Actually I also wanted to know if you found a method to link fesvr with Questasim. If not how are viewing waveforms. Are you dumping the vcd file from verilator and running it on Questasim?

**Comment by zarubaf** [comment]
`fesvr` integration is coming with the new debug module #3
