### ISSUE TITLE
Instruction start at 0x80000000

### ISSUE THREAD

**Issue by ShravanSubbaraman** [pulp-platform/ariane#49]
Why is there a specific need for the instruction to start at 0x80000000?

**Comment by zarubaf** [comment]
Actually there is none. The core doesn't care where it is fetching instructions from. The TB however does for certain reasons:
- Checking integrity of the data-cache
- Instantiating the core with the right boot address and start address for cache-able accesses.

**Comment by zarubaf** [comment]
I've seen that Spike also jumps to that address and Rocket also does. But its nothing which is written in the spec. So I've just decided to also start there as it would allow for most SW re-use.
