### ISSUE TITLE
Error in "make build"

### ISSUE THREAD

**Issue by merchantf** [pulp-platform/ariane#53]
Hi,

I am getting following error in "make build"

g++ -c -fPIC -m64 -std=c++0x -I/include -shared -o work/elf_dpi.o -c tb/dpi/elfdpi.cc
tb/dpi/elfdpi.cc:26:22: fatal error: vpi_user.h: No such file or directory

Can you please help me with that?

Farhad

**Comment by zarubaf** [comment]
I guess the include path is not correct for you. Make sure `QUESTASIM_HOME` points to the install dir of your ModelSim.
